### ISSUE TITLE
Work in Production environment?

### ISSUE THREAD

**Issue by julgq** [anicdh/bitcoin_flutter#12]
I am working in Flutter App, I need this library to work generating new bitcoin adress, and make transactions.

Do you recommend work in production with this library?
Do you know some flutter app using the library in production?

Thanks.

**Comment by longhoangwkm** [comment]
We are using it on production, For basic functions as generating new bitcoin adress, and make transactions.It's safe to use, Another functions i can not make sure 100%. We are trying to improve this lib. Thanks for using this lib, feel free to open if you have any issues.
