### ISSUE TITLE
Is P2WPKH support planned?

### ISSUE THREAD

**Issue by RohanKapurDEV** [anicdh/bitcoin_flutter#14]

**Comment by longhoangwkm** [comment]
We will support soon, Thanks!

**Comment by RohanKapurDEV** [comment]
Are you building on top of your fork only or will the code eventually merge with this repo?

**Comment by longhoangwkm** [comment]
I am responsible for developing this repo from now on

**Comment by SFzxc** [comment]
https://github.com/anicdh/bitcoin_flutter/pull/17
Build segwit Tx is coming soon

**Comment by RohanKapurDEV** [comment]
Just saw that P2WPKH support was just merged in which is amazing. I'm glad people are actually working on this library and that it has not been forgotten. Good job guys.
