### ISSUE TITLE
new HDWallet(seed) is not work

### ISSUE THREAD

**Issue by YDJSZY** [anicdh/bitcoin_flutter#15]
new HDWallet(seed) is not work. It need other arguments.

**Comment by trongdth** [comment]
Use this one: HDWallet.fromSeed(seed)

**Comment by longhoangwkm** [comment]
as @trongdth said `new HDWallet.fromSeed(seed)`
https://github.com/anicdh/bitcoin_flutter/blob/e20962e681a6eacb85b316da4cc2589b7b604f64/test/bitcoin_test.dart#L9.
Feel free to open if you have any issues, Thanks!
