### ISSUE TITLE
can you provide a example about send btc transaction?

### ISSUE THREAD

**Issue by YDJSZY** [anicdh/bitcoin_flutter#16]
can you provide a example about send btc transaction?

**Comment by longhoangwkm** [comment]
Hi @YDJSZY , here you are https://github.com/anicdh/bitcoin_flutter/blob/master/test/integration/transactions_test.dart#L7

**Comment by longhoangwkm** [comment]
Closing. Feel free to open if you have any issues, Thanks!

**Comment by YDJSZY** [comment]
Thanks!
