### ISSUE TITLE
can I  broadcast a Transaction to the Bitcoin network if I use this plugin

### ISSUE THREAD

**Issue by YunhuiLiu140502** [anicdh/bitcoin_flutter#20]
can I  broadcast a Transaction to the Bitcoin network if I use this plugin

**Comment by longhoangwkm** [comment]
@YunhuiLiu140502, Unfortunately, this is not possible, this is an offline library that does not link the bitcoind node. If you wanna broadcast your raw hex transaction, you have to install your own bitcoind node, or using UI like https://www.blockstream.info/tx/push, or finding a third party service which providing public broadcast API like https://www.blockcypher.com/quickstart/. Just Sign Up and generate a secret token to call their API

**Comment by YunhuiLiu140502** [comment]
if I have a bitcoind node,How do you use it in flutter.

**Comment by longhoangwkm** [comment]
@YunhuiLiu140502 , You can using https://pub.dev/packages/dio package to call `sendrawtransaction` JSON RPC API to your own node

**Comment by YunhuiLiu140502** [comment]
@longhoangwkm Ok. Thank you for your answer. Thank you very much
