### ISSUE TITLE
Bitcoin_flutter is still on version 1.0.7 on pub.dev

### ISSUE THREAD

**Issue by RohanKapurDEV** [anicdh/bitcoin_flutter#21]
Hey, I noticed that you guys recently added P2WPKH support which is fantastic. The problem is that the library has not been updated on pub.dev so I can't really use these features.

Here is the link: https://pub.dev/packages/bitcoin_flutter/versions

As you can see in the 'Versions' tab, the last time this package was officially updated on pub.dev was Apr 21, 2019. 

That's all.    :)

**Comment by longhoangwkm** [comment]
Hi @RohanKapurDEV , Sorry for that, my friend forgot to publish. I just updated. 
https://pub.dev/packages/bitcoin_flutter/versions/1.1.0 Here you are.

**Comment by longhoangwkm** [comment]
Notice that, It only invoke generate segwit address feature not segwit transaction builder yet. I will develop it at this weekend

**Comment by RohanKapurDEV** [comment]
> Notice that, It only invoke segwit address generating feature not segwit transaction builder yet. I will develop it at this weekend

Hey is there any update on support for spending native segwit outputs using the transaction builder? My project is approaching the stage where that is necessary and I was hoping it can be worked on soon.

Let me know if i can be of any help

**Comment by longhoangwkm** [comment]
Hi @RohanKapurDEV, Sorry for hearing that, i'm developing but not done yet and not enough test cover, i would try my best to finish this feature in this week. Many thanks. So many thing to do.

**Comment by longhoangwkm** [comment]
PRs are welcome. We are cloning from bitcoinjs. You can take alook, we need modify transaction.dart and transaction_builder.dart

**Comment by SFzxc** [comment]
I moved this feature to here https://github.com/anicdh/bitcoin_flutter/issues/26. Please follow this issue.
