### ISSUE TITLE
Invalid version or Network mismatch

### ISSUE THREAD

**Issue by Merrick17** [anicdh/bitcoin_flutter#22]
Hello I am Trying to create a Transaction , but i always get the error Invalid version or Network mismatch i am using testnet adresses this is my log..
 Bitcoin Adress moZ3hBUMbu5pFaodrsLCKg76U53NdmDVqc
Bitcoin Second Address muYEstcvt7ZyLUv6DRXNX592NF7RGSUEAo
Unhandled exception:
Invalid argument(s): Invalid version or Network mismatch
#0      P2PKH._getDataFromAddress (package:bitcoin_flutter/src/payments/p2pkh.dart:87:7)
#1      P2PKH._init (package:bitcoin_flutter/src/payments/p2pkh.dart:22:7)
#2      new P2PKH (package:bitcoin_flutter/src/payments/p2pkh.dart:18:5)
#3      addressToOutputScript (package:bitcoin_flutter/src/transaction_builder.dart:286:11)
#4      TransactionBuilder.addOutput (package:bitcoin_flutter/src/transaction_builder.dart:71:22)
#5      CreateWallet.generateTransaction (file:///home/safouene/crypto_test/main.dart:152:11)
#6      main (file:///home/safouene/crypto_test/main.dart:178:8)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by longhoangwkm** [comment]
Hi @Merrick17, Would you mind if show me your full code ?!. I guess you didn't set network is testnet. Default network is mainnet

**Comment by Merrick17** [comment]
Sure , here is the part where I got stuck ... 
generateTransaction(WIF,desAdress,amount,prev)

{ 
   final myInfo = bitcoinFlutter.ECPair.fromWIF(WIF);
  final txb = new bitcoinFlutter.TransactionBuilder(network: testnet);
  txb.setVersion(1);
      txb.addInput(prev, 0);
      txb.addOutput(desAdress, amount);
      txb.sign(0, myInfo);
    var transaction=txb.build().toHex(); 
  print(transaction.toString()); 

}

![test_network](https://user-images.githubusercontent.com/25400839/72327202-ead20d80-36b0-11ea-95e2-71242208710e.png)

**Comment by SFzxc** [comment]
Hi @Merrick17,
Here are how can using testnet in this lib:

```dart
// Generate a testnet address from <pubkey>

import 'package:bitcoin_flutter/src/models/networks.dart' as NETWORKS;
final address = new P2PKH(data: new PaymentData(pubkey: <pubkey>), network: NETWORKS.testnet).data.address;
```
