### ISSUE TITLE
Validating addresses

### ISSUE THREAD

**Issue by jangerhard** [anicdh/bitcoin_flutter#24]
Is it possible to use this library to validate base58 addresses? Will there be segwit support as well?

**Comment by SFzxc** [comment]
This lib still in early stage. I'm developing feature based on user request. i will add validation soon. Thanks for requesting

**Comment by SFzxc** [comment]
PRs are welcome!

**Comment by SFzxc** [comment]
@jangerhard Please take a look at testcase to use https://github.com/anicdh/bitcoin_flutter/blob/master/test/address_test.dart#L14

Thank you!

**Comment by SFzxc** [comment]
Btw, long address like `tb1qqqqqp399et2xygdj5xreqhjjvcmzhxw4aywxecjdzew6hylgvsesrxh6hy `  is not support yet. It correct address but current lib treat it as invalid.

Feel free to reopen issue if you get any problem. Many thanks

**Comment by longhoangwkm** [comment]
published new code as 2.0.0
